### ISSUE TITLE
"/msg gitinfo .voice" seems to be counterproductive, if it has any effect at all

### ISSUE THREAD

**Issue by ToBeFree** [jast/gitinfo#15]
Please correct me if I am wrong, but while the .voice command seems to be a nice idea in case the channel is e.g. +m or +q $~a, it does not seem to do what it appears to be intended for.

The topic of #git on freenode says:

> Getting "cannot send to channel"? /msg gitinfo .voice

(note: The channel is currently +Ccnt, so the default state of the channel seems to be unmoderated)

So this command seems to be made for a situation in which spammers or other unwanted people caused the operators to prevent anyone except some trusted/registered users from talking. Allowing anyone, even bots and spammers, to easily become a part of the privileged group just by sending a very easily automatable command, breaks this concept. This way to become voiced is so easily automatable that I have added it to my commands-sent-after-joining list in HexChat and IRCCloud. There is no additional check, no email sent (as opposed to freenode's NickServ registration), and all needed to break the whole point of +m and +q $~a in #git is a single message. 

But this command does not only seem to be pointless, it can also cause undesired side effects. For example, channel voice will allow any spammer/bot to bypass the IRCd's private message spam prevention.[\[1\]][1] Normally, when someone sends a query to many people in a row, they get an error message telling them that they are "changing targets too fast". This prevents someone from joining a channel to get a list of users that will then receive yet-another-freenode-pornspam-query. However, because there might be bots that have legitimate reasons to message, e.g., every user joining a specific channel, or because voice normally is a sign of trust by the channel operators*, people who are voiced in a specific channel can freely query everyone in that channel without any additional limits.

(*UnrealIRCd even allows voiced users to bypass the +C restriction that blocks channel-wide CTCPs. This is not relevant to freenode, but it confirms that voice is usually interpreted as a sign of trust)

So - if I understand the situation correctly - the .voice command adds a useless layer of pseudo-security that can even be counterproductive. :-/

[1]: http://www.stack.nl/~jilles/irc/charybdis-oper-guide/ucommands.htm#AEN294
\[1\]: http://www.stack.nl/~jilles/irc/charybdis-oper-guide/ucommands.htm#AEN294 (4.1.3. CPRIVMSG)

**Comment by jast** [comment]
.voice is meant for when the channel is set to +q $~a, which it sometimes is when spammer activity is high. It has shown to be highly effective in that kind of situation, despite all the very valid flaws you noticed in this approach – the bet here is that true spammers don't actually bother tailor-fitting their spamming systems to work with gitinfo, because investing time into breaking one layer of protection in a smallish community is unlikely to appeal to them: they can expect that if they break this, #git will respond by raising the bar, so any gains made from the investment will be very temporary. So far this bet has worked out in practice.

Regarding the target limiting, have you actually observed people abusing the .voice mechanism specifically for bypassing that? I'd prefer to not have to think up a new way to deal with spammer attacks as long as the current way isn't actively being abused.

**Comment by jast** [comment]
Closing only due to inactivity; please feel free to comment or re-open.

**Comment by ToBeFree** [comment]
Oh, I missed the notification 26 about your reply 26 days ago :D
No, I have not seen anyone abusing .voice and what you said is probably true, so I guess closing the bug is fine.^^
