### ISSUE TITLE
Trigger "!oops" matches "!ops"

### ISSUE THREAD

**Issue by Zarthus** [jast/gitinfo#18]
Presumably not a direct bug of gitinfo, but a special case for !ops to be ignored may be worth considering.

**Comment by jast** [comment]
FWIW I understood the original title better. :)

This is because gitinfo does shortest infix matching (if an exact match isn't found, it finds the shortest trigger name that contains the query). Some time ago I added a feature for silencing specific triggers (it's not really documented, though). I just added a silencing entry for !ops in the #git bot which should take care of this. HTH.
